version: '3.9'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: hospital_call
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html:ro

  mysql-client:
    image: mysql:latest
    container_name: mysql-client
    depends_on:
      - mariadb
    entrypoint: ["tail", "-f", "/dev/null"]

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  flask_app:
    build: .
    container_name: flask_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mariadb
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=hospital_call
    depends_on:
      - mariadb

volumes:
  mariadb_data:

networks:
  ppp_net:
    driver: bridge