CREATE TABLE IF NOT EXISTS habitacion (
    id INT AUTO_INCREMENT PRIMARY KEY,
    numero INT NOT NULL,
    planta INT NOT NULL
);

CREATE TABLE IF NOT EXISTS cama (
    id INT AUTO_INCREMENT PRIMARY KEY,
    codigo VARCHAR(10) UNIQUE NOT NULL,
    id_habitacion INT NOT NULL,
    FOREIGN KEY (id_habitacion) REFERENCES habitacion(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS asistente (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    codigo_acceso VARCHAR(10) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS llamada (
    id INT AUTO_INCREMENT PRIMARY KEY,
    hora_llamada TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id_cama INT NOT NULL,
    estado BOOLEAN  NOT NULL DEFAULT 0,
    FOREIGN KEY (id_cama) REFERENCES cama(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS presencia (
    id INT AUTO_INCREMENT PRIMARY KEY,
    hora_llegada TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id_llamada INT UNIQUE NOT NULL,
    id_asistente INT NOT NULL,
    FOREIGN KEY (id_llamada) REFERENCES llamada(id) ON DELETE CASCADE,
    FOREIGN KEY (id_asistente) REFERENCES asistente(id) ON DELETE CASCADE
);
